In [1]:
import infection

ModuleNotFoundError: No module named 'infection'

In [ ]:
infection.ccc

'a'

In [8]:
import infection as inf

ModuleNotFoundError: No module named 'infection'

In [13]:
import numpy as np

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
class Mundo:

  def __init__(self, n_columnas, n_filas):
    self.numero_columnas = n_columnas
    self.numero_filas = n_filas
    self.mapa = np.zeros((n_filas, n_columnas), dtype=int)

  def ocupacion_inicial(self, ocupacion):
    numero_celdas_ocupadas = int(self.numero_columnas * self.numero_filas * ocupacion)

    contador = 0
    while contador < numero_celdas_ocupadas:
      ii = np.random.randint(0, self.numero_filas)
      jj = np.random.randint(0, self.numero_columnas)
      if (self.mapa[ii, jj] == 0):
        self.mapa[ii, jj] = 1
        contador = contador + 1

In [33]:
mundo_1 = Mundo(100, 200)

In [35]:
mundo_1.mapa

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
mundo_1.ocupacion_inicial(0.3328676)

665


In [27]:
np.random.randint(0,10,2)

array([2, 5])

In [22]:
np.round(0.4345)

np.float64(0.0)

In [12]:
mundo_1.prueba("Hola mundo")

TypeError: Mundo.prueba() takes 1 positional argument but 2 were given

In [4]:
mundo_1.numero_columnas

100

In [5]:
mundo_2 = Mundo(100, 60)

In [6]:
mundo_2.numero_filas

60